name: Terraform Deployment to AWS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["provide render development environment"]
    types:
      - completed

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      - name: Terraform Init
        working-directory: ./infra
        run: terraform init
      - name: Terraform Plan
        working-directory: ./infra
        run: terraform plan
      - name: Terraform Apply
        working-directory: ./infra
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
