#create new yml 
#checkout + build docker image + push de l'image (sur le bon registry)
#declenchement a la validation avec workflow_dispatch
#declenchement a travers un workflow_run du precedent workflow

name: Docker Publish to GHCR

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["lint, test, and run containerized flask app"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/loise/containerized-devops-workflow/monapp:latest .

      
      - name: Push Docker image to ghcr
        run: docker push ghcr.io/loise/containerized-devops-workflow/monapp:latest
